<script>
  import ArticleEditor from "$lib/components/ArticleEditor.svelte";
  import CardImageEditor from "$lib/components/CardImageEditor.svelte";
  import { articleSlug } from "$lib/article-slug.js";
  let { data, form } = $props();

  const blankArticle = { id: "", title: "", category: "Working Paper", status: "Draft", date: "", tags: [], abstract: "", metrics: [], body: [], method: "", cardMediaId: "", cardImage: null, content: { type: "doc", content: [] }, figures: [] };
  const blankExperience = { id: "", company: "", role: "", period: "", location: "", highlights: [], isCurrent: false };
  const blankEducation = { id: "", degree: "", school: "", period: "", location: "", note: "", isCurrent: false };
  let editingArticle = $derived(data.authenticated && data.section === "articles" && data.editId ? (data.editId === "new" ? blankArticle : data.content.articles.find((item) => item.id === data.editId)) : null);
  let editingExperience = $derived(data.authenticated && data.section === "experience" && data.editId ? (data.editId === "new" ? blankExperience : data.content.experiences.find((item) => item.id === data.editId)) : null);
  let editingEducation = $derived(data.authenticated && data.section === "education" && data.editId ? (data.editId === "new" ? blankEducation : data.content.education.find((item) => item.id === data.editId)) : null);
  const richContent = (article) => article.content || { type: "doc", content: (article.body || []).map((text) => ({ type: "paragraph", content: text ? [{ type: "text", text }] : [] })) };
  const metricText = (article) => (article.metrics || []).map((item) => `${item.label} | ${item.value}`).join("\n");
  const attachmentFor = (article) => (data.content.attachments || []).filter((item) => item.articleId === article.id);
  const formatBytes = (size) => size >= 1024 * 1024 ? `${(size / (1024 * 1024)).toFixed(1)} MB` : `${Math.max(1, Math.round(size / 1024))} KB`;
  const mediaUsage = (id) => (data.content.articles || []).filter((article) => article.cardMediaId === id || JSON.stringify(article.content || {}).includes(`/media/${id}`) || JSON.stringify(article.body || []).includes(`[[image:${id}]]`) || JSON.stringify(article.embed || {}).includes(`/media/${id}`));
</script>

<svelte:head><title>Publishing studio — {data.authenticated ? data.content.profile.name : "Lorenzo Pulcini"}</title><meta name="robots" content="noindex,nofollow" /></svelte:head>

{#if !data.authenticated}
  <main id="main" class="auth-wrap shell"><section class="auth-card"><p class="eyebrow">Protected publishing studio</p><h1>Write, build, and publish.</h1><p>Sign in with an explicitly authorized GitHub account to manage the site and create interactive research articles.</p>{#if data.configured}<a class="button" href="/auth/github">Continue with GitHub →</a>{:else}<p class="notice">GitHub OAuth is not configured for this environment. Add the values from <code>.env.example</code> to enable sign-in.</p>{/if}</section></main>
{:else}
  <main id="main">
    <div class="shell admin-shell">
      <header class="admin-head"><div><p class="eyebrow">Publishing studio</p><h1>{data.content.profile.name}</h1></div><div class="admin-user"><span>Signed in as {data.user.login}</span><form method="post" action="/auth/logout"><input type="hidden" name="csrf" value={data.user.csrf} /><button class="link-button" type="submit">Sign out</button></form></div></header>
      <nav class="admin-nav" aria-label="Admin sections"><a href="/admin?section=profile" aria-current={data.section === "profile" ? "page" : undefined}>Site settings</a><a href="/admin?section=articles" aria-current={data.section === "articles" ? "page" : undefined}>Articles</a><a href="/admin?section=experience" aria-current={data.section === "experience" ? "page" : undefined}>Experience</a><a href="/admin?section=education" aria-current={data.section === "education" ? "page" : undefined}>Education</a></nav>
      <section class="admin-main">
        {#if data.notice}<p class="notice" role="status">{data.notice}</p>{/if}
        {#if form?.message}<p class="notice notice--error" role="alert">{form.message}</p>{/if}

        {#if data.section === "profile"}
          <div class="admin-actions"><div><p class="eyebrow">Site content</p><h2>Profile and contact details</h2></div><a class="button secondary" href="/" target="_blank" rel="noopener noreferrer">View site ↗</a></div>
          <form class="editor" method="post" action="?/profile"><input type="hidden" name="csrf" value={data.user.csrf} /><div class="form-grid">
            <label class="field"><span class="label">Name</span><input name="name" value={data.content.profile.name} required maxlength="120" /></label><label class="field"><span class="label">Availability</span><input name="availability" value={data.content.profile.availability} maxlength="200" /></label>
            <label class="field full"><span class="label">Eyebrow</span><input name="eyebrow" value={data.content.profile.eyebrow} maxlength="240" /></label><label class="field full"><span class="label">Homepage headline</span><textarea name="headline" rows="2" maxlength="300" required>{data.content.profile.headline}</textarea></label><label class="field full"><span class="label">Homepage introduction</span><textarea name="intro" rows="4" maxlength="1200" required>{data.content.profile.intro}</textarea></label><label class="field full"><span class="label">About</span><textarea name="about" rows="6" maxlength="4000" required>{data.content.profile.about}</textarea></label>
            <label class="field"><span class="label">Email</span><input type="email" name="email" value={data.content.profile.email} required /></label><label class="field"><span class="label">Phone</span><input name="phone" value={data.content.profile.phone} /></label><label class="field"><span class="label">Location</span><input name="location" value={data.content.profile.location} /></label><label class="field"><span class="label">LinkedIn URL</span><input type="url" name="linkedin" value={data.content.profile.linkedin} /></label><label class="field"><span class="label">GitHub URL</span><input type="url" name="github" value={data.content.profile.github} /></label>
          </div><div class="form-actions"><button class="button" type="submit">Save settings</button></div></form>
          <section class="backup-panel"><div><p class="eyebrow">Content backup</p><h2>Export or restore site data</h2><p class="muted">The JSON backup includes article figure code and data. Uploaded file bytes remain in the data volume.</p></div><div class="backup-actions"><a class="button secondary" href="/admin/backup">Download backup</a><form method="post" action="?/restore" enctype="multipart/form-data"><input type="hidden" name="csrf" value={data.user.csrf} /><label class="file-field"><span class="label">JSON backup (up to 5 MB)</span><input type="file" name="backup" accept="application/json,.json" required /></label><label class="field checkbox"><input type="checkbox" name="replace" value="yes" required /><span class="label">Replace all current site data.</span></label><button class="button" type="submit">Restore backup</button></form></div></section>

        {:else if data.section === "articles"}
          {#if editingArticle}
            <div class="admin-actions"><div><p class="eyebrow">Article workspace</p><h2>{editingArticle.id ? `Edit “${editingArticle.title}”` : "Create a new article"}</h2></div><a class="button secondary" href="/admin?section=articles">Back to articles</a></div>
            <form class="editor article-editor-form" method="post" action="?/saveArticle"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={editingArticle.id} /><div class="form-grid">
              <section class="article-basics field full"><p class="eyebrow">Publication details</p><div class="form-grid"><label class="field full"><span class="label">Title</span><input name="title" value={editingArticle.title} required maxlength="240" placeholder="A precise, useful title" /></label><label class="field"><span class="label">Category</span><input name="category" value={editingArticle.category} required maxlength="120" /></label><label class="field"><span class="label">Status</span><select name="status" value={editingArticle.status}>{#each ["Article", "Preprint", "Working Paper", "Peer Reviewed", "Draft", "Thesis"] as status}<option value={status} selected={editingArticle.status === status}>{status}</option>{/each}</select></label><label class="field full"><span class="label">Date / attribution</span><input name="date" value={editingArticle.date} maxlength="200" /></label><label class="field full"><span class="label">Tags</span><input name="tags" value={(editingArticle.tags || []).join(", ")} maxlength="500" placeholder="asset pricing, machine learning, options" /></label>{#key editingArticle.id}<CardImageEditor media={data.content.media || []} initialMediaId={editingArticle.cardMediaId || ""} initialSettings={editingArticle.cardImage} />{/key}<label class="field full"><span class="label">Abstract</span><textarea name="abstract" rows="4" maxlength="2000" placeholder="A short promise to the reader">{editingArticle.abstract}</textarea></label><label class="field"><span class="label">Metrics (label | value)</span><textarea name="metrics" rows="4" maxlength="2000">{metricText(editingArticle)}</textarea></label><label class="field"><span class="label">Method note</span><textarea name="method" rows="4" maxlength="3000">{editingArticle.method}</textarea></label></div></section>
              <ArticleEditor content={richContent(editingArticle)} media={data.content.media || []} initialFigures={editingArticle.figures || []} />
            </div><div class="sticky-save"><span>Changes publish immediately when saved.</span><div><a class="button secondary" href="/admin?section=articles">Cancel</a><button class="button" type="submit">Save and publish</button></div></div></form>

            <section class="media-panel"><div><p class="eyebrow">Media library</p><h2>Upload article images</h2><p class="muted">Uploaded images become available in the editor toolbar and as article card media. Images must be removed from every article before they can be deleted.</p><form method="post" action="?/uploadMedia" enctype="multipart/form-data" class="media-upload"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="articleId" value={editingArticle.id} /><label class="field"><span class="label">Accessible description</span><input name="alt" maxlength="300" /></label><label class="field"><span class="label">PNG, JPEG, GIF, or WebP</span><input type="file" name="image" accept="image/png,image/jpeg,image/gif,image/webp" required /></label><button class="button" type="submit">Upload</button></form></div><div class="media-library">{#each data.content.media || [] as item}{@const usage = mediaUsage(item.id)}<article class="media-item"><img src={`/media/${item.id}`} alt={item.alt || ""} loading="lazy" /><div><strong>{item.alt || "Untitled image"}</strong><code>/media/{item.id}</code><div class="media-item-actions">{#if usage.length}<span>Used by {usage.length} {usage.length === 1 ? "article" : "articles"}</span>{/if}<form method="post" action="?/deleteMedia" onsubmit={(event) => !confirm(`Permanently delete “${item.alt || "this image"}”?`) && event.preventDefault()}><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={item.id} /><input type="hidden" name="articleId" value={editingArticle.id} /><button class="link-button danger" type="submit" disabled={usage.length > 0} title={usage.length ? "Remove the image from its articles first" : "Delete image"}>Delete</button></form></div></div></article>{/each}</div></section>
            <section class="attachment-panel"><div><p class="eyebrow">Attachments</p><h2>Attach downloadable PDFs</h2><p class="muted">Save a new article before attaching its first document.</p><form method="post" action="?/uploadAttachment" enctype="multipart/form-data" class="media-upload"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="articleId" value={editingArticle.id} /><label class="field"><span class="label">Download label</span><input name="title" maxlength="240" required /></label><label class="field"><span class="label">PDF up to 20 MB</span><input type="file" name="pdf" accept="application/pdf,.pdf" required /></label><button class="button" type="submit" disabled={!editingArticle.id}>Attach</button></form></div><div class="attachment-list">{#each attachmentFor(editingArticle) as item}<div class="attachment-row"><a class="attachment-item" href={`/attachments/${item.id}`}>{item.title}<span>PDF · {formatBytes(item.size)}</span></a><form method="post" action="?/deleteAttachment" onsubmit={(event) => !confirm(`Permanently delete “${item.title}”?`) && event.preventDefault()}><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={item.id} /><button class="link-button danger" type="submit">Delete</button></form></div>{/each}</div></section>
          {:else}
            <div class="admin-actions"><div><p class="eyebrow">Publishing</p><h2>Articles and publications</h2><p class="muted">Use the arrow controls to choose the order shown on the homepage.</p></div><a class="button" href="/admin?section=articles&edit=new">+ New article</a></div><div class="admin-list">{#each data.content.articles as article, index}<article class="admin-row"><div><h3>{article.title}</h3><p>Position {index + 1} · {article.category} · {article.status} · {(article.figures || []).length} figures</p></div><div class="row-actions"><div class="order-actions" role="group" aria-label={`Reorder “${article.title}”`}><form method="post" action="?/reorderArticle"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={article.id} /><input type="hidden" name="direction" value="up" /><button class="order-button" type="submit" disabled={index === 0} aria-label={`Move “${article.title}” up`} title="Move up">↑</button></form><form method="post" action="?/reorderArticle"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={article.id} /><input type="hidden" name="direction" value="down" /><button class="order-button" type="submit" disabled={index === data.content.articles.length - 1} aria-label={`Move “${article.title}” down`} title="Move down">↓</button></form></div><a class="link-button" href={`/articles/${articleSlug(article.title)}`} target="_blank" rel="noopener noreferrer">View</a><a class="link-button" href={`/admin?section=articles&edit=${article.id}`}>Edit</a><form method="post" action="?/deleteArticle" onsubmit={(event) => !confirm(`Delete “${article.title}”?`) && event.preventDefault()}><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={article.id} /><button class="link-button danger" type="submit">Delete</button></form></div></article>{/each}</div>
          {/if}

        {:else if data.section === "experience"}
          {#if editingExperience}<div class="admin-actions"><h2>{editingExperience.id ? "Edit experience" : "Add experience"}</h2></div><form class="editor" method="post" action="?/saveExperience"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={editingExperience.id} /><div class="form-grid"><label class="field"><span class="label">Company</span><input name="company" value={editingExperience.company} required /></label><label class="field"><span class="label">Role</span><input name="role" value={editingExperience.role} required /></label><label class="field"><span class="label">Period</span><input name="period" value={editingExperience.period} /></label><label class="field"><span class="label">Location</span><input name="location" value={editingExperience.location} /></label><label class="field full"><span class="label">Highlights (one per line)</span><textarea name="highlights" rows="7">{editingExperience.highlights.join("\n")}</textarea></label><label class="field checkbox"><input type="checkbox" name="isCurrent" value="1" checked={editingExperience.isCurrent} /><span class="label">Current position</span></label></div><div class="form-actions"><a class="button secondary" href="/admin?section=experience">Cancel</a><button class="button">Save experience</button></div></form>{:else}<div class="admin-actions"><h2>Experience</h2><a class="button" href="/admin?section=experience&edit=new">+ Add entry</a></div><div class="admin-list">{#each data.content.experiences as item}<article class="admin-row"><div><h3>{item.role} — {item.company}</h3><p>{item.period} · {item.location}</p></div><div class="row-actions"><a class="link-button" href={`/admin?section=experience&edit=${item.id}`}>Edit</a><form method="post" action="?/deleteExperience"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={item.id} /><button class="link-button danger">Delete</button></form></div></article>{/each}</div>{/if}

        {:else if data.section === "education"}
          {#if editingEducation}<div class="admin-actions"><h2>{editingEducation.id ? "Edit education" : "Add education"}</h2></div><form class="editor" method="post" action="?/saveEducation"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={editingEducation.id} /><div class="form-grid"><label class="field"><span class="label">Degree</span><input name="degree" value={editingEducation.degree} required /></label><label class="field"><span class="label">School</span><input name="school" value={editingEducation.school} required /></label><label class="field"><span class="label">Period</span><input name="period" value={editingEducation.period} /></label><label class="field"><span class="label">Location</span><input name="location" value={editingEducation.location} /></label><label class="field full"><span class="label">Note</span><textarea name="note" rows="5">{editingEducation.note}</textarea></label><label class="field checkbox"><input type="checkbox" name="isCurrent" value="1" checked={editingEducation.isCurrent} /><span class="label">Current</span></label></div><div class="form-actions"><a class="button secondary" href="/admin?section=education">Cancel</a><button class="button">Save education</button></div></form>{:else}<div class="admin-actions"><h2>Education</h2><a class="button" href="/admin?section=education&edit=new">+ Add entry</a></div><div class="admin-list">{#each data.content.education as item}<article class="admin-row"><div><h3>{item.degree} — {item.school}</h3><p>{item.period} · {item.location}</p></div><div class="row-actions"><a class="link-button" href={`/admin?section=education&edit=${item.id}`}>Edit</a><form method="post" action="?/deleteEducation"><input type="hidden" name="csrf" value={data.user.csrf} /><input type="hidden" name="id" value={item.id} /><button class="link-button danger">Delete</button></form></div></article>{/each}</div>{/if}
        {/if}
      </section>
    </div>
  </main>
{/if}
